server {	
	listen 80;
	server_name _;

	root /var/www/html/current;
	index index.html;

	location / {
		try_files $uri $uri/ =404;
	}

	location /staging/ {
		alias /var/www/staging/current/;
	}

	location /health {
		return 200 'healthy';
		add_header Content-Type text/plain;
	}
}
