name: Deploy Website

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Adding EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 16.171.141.46 >> ~/.ssh/known_hosts

      - name: Prepare server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@16.171.141.46 "

            set -e

            #Install Nginx if not installed
            if ! command -v nginx > dev/null;
              sudo apt update
              sudo apt install nginx -y
            fi

            #Create necessary directories
            sudo mkdir -p /var/www/releases

            #Set ownership
            sudo chown -R ubuntu:ubuntu /var/www

            #Configure nginx root to /current
            sudo sed -i 's|root /var/www/html;|root /var/www/html/current;|' etc/nginx/sites-available/default

            #Restart nginx
            sudo systemctl restart nginx

          "

      - name: Deploy to EC2 without downtime
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@16.171.141.46 "
            set -e  #Exit if any command fails

            #Ensure release folder exists
            mkdir -p /var/www/releases

            #Save previous release (if current exists)
            if [ -L /var/www/html/current ]; then
              PREV_RELEASE=\$(readlink /var/www/html/current)
            else
              PREV_RELEASE=''
            fi

            #Create a unique release folder with timestamp
            NEW_RELEASE=/var/www/releases/release-$(date +%s)
            mkdir -p \$NEW_RELEASE
            echo "Deploying to:" \$NEW_RELEASE

            #Upload all files to the new release
            rsync -av --delete ~/devops-project/web/ \$NEW_RELEASE

            #Update symlink so that Nginx serves the new release
            ln -sfn \$NEW_RELEASE /var/www/html/current
            echo "Deployment complete"

            #Verify deployment
            if [ ! -f /var/www/html/current ]; then
              echo "Deplyment failed, rolling back..."
              if [ -n \"\$PREV_RELEASE\" ]; then
                ln -sfn \$PREV_RELEASE /var/www/html/current
                echo "Rollback complete"
              fi
              exit 1
            fi

            echo "Deployment successful"

            #Keep last 3 releases, delete older ones
            ls -dt /var/www/releases/* | tail -n +4 | xargs rm -rf
          "
