name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Adding EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 51.20.43.183 >> ~/.ssh/known_hosts

      - name: Prepare server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@51.20.43.183 "
            sudo apt update &&\
            sudo apt install nginx -y &&\
            sudo mkdir -p /var/www/html
            sudo chown -R ubuntu:ubuntu /var/www/html
          "

      - name: Sync web folder to server
        run: |
          rsync -av --delete ./web/ ubuntu@51.20.43.183:/var/www/html

      - name: Deployment Success
        run: echo "Deployment completed successfully"
